# Generated by Django 4.2.7 on 2024-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='version',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
